"""update usuario and roles

Revision ID: 34fe24e89a24
Revises: 58e5364d13e9
Create Date: 2026-02-25 22:14:47.512638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34fe24e89a24'
down_revision: Union[str, Sequence[str], None] = '58e5364d13e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('afiliacion', 'nombre',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    op.alter_column('sede', 'direccion',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('usuario', 'password',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('usuario', 'persona_carnet_usbid',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.create_foreign_key(None, 'usuario', 'carnet', ['persona_carnet_usbid'], ['usbid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.alter_column('usuario', 'persona_carnet_usbid',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    op.alter_column('usuario', 'password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=45),
               nullable=True)
    op.alter_column('sede', 'direccion',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('afiliacion', 'nombre',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    # ### end Alembic commands ###
