"""second migration

Revision ID: 58e5364d13e9
Revises: f6468878a69f
Create Date: 2026-02-25 00:13:15.945747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e5364d13e9'
down_revision: Union[str, Sequence[str], None] = 'f6468878a69f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('afiliacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=True),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=True),
    sa.Column('duracion_vigencia_anos', sa.Integer(), nullable=True),
    sa.Column('requiere_pago_estacionamiento', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrera',
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=True),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('departamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=False),
    sa.Column('descripcion', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('nacionalidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('permisos',
    sa.Column('nombre', sa.String(length=45), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('nombre')
    )
    op.create_table('punto_acceso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=False),
    sa.Column('tipo', sa.Enum('Torniquete', 'Garita', 'Puerta', name='tipopuntoaccesoenum'), nullable=True),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('nombre', sa.String(length=45), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('nombre')
    )
    op.create_table('sede',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=False),
    sa.Column('direccion', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('status_carnet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('status_persona_afiliacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('acceso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_acceso', sa.Enum('Entrada', 'Salida', name='tipoaccesoenum'), nullable=True),
    sa.Column('fecha_hora', sa.Time(), nullable=True),
    sa.Column('resultado', sa.Enum('Permitido', 'Denegado', name='resultadoenum'), nullable=True),
    sa.Column('punto_acceso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['punto_acceso_id'], ['punto_acceso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carnet',
    sa.Column('usbid', sa.String(length=10), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('qr_token', sa.String(length=100), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status_carnet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['status_carnet_id'], ['status_carnet.id'], ),
    sa.PrimaryKeyConstraint('usbid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('rol_has_permisos',
    sa.Column('rol_nombre', sa.String(length=45), nullable=False),
    sa.Column('permisos_nombre', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['permisos_nombre'], ['permisos.nombre'], ),
    sa.ForeignKeyConstraint(['rol_nombre'], ['rol.nombre'], ),
    sa.PrimaryKeyConstraint('rol_nombre', 'permisos_nombre')
    )
    op.create_table('usuario',
    sa.Column('usbid', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=45), nullable=True),
    sa.Column('descripcion', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('rol_nombre', sa.String(length=45), nullable=False),
    sa.Column('remote_ip', sa.String(length=45), nullable=True),
    sa.Column('remote_access_from', sa.String(length=45), nullable=True),
    sa.Column('persona_carnet_usbid', sa.String(length=45), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamento.id'], ),
    sa.ForeignKeyConstraint(['rol_nombre'], ['rol.nombre'], ),
    sa.PrimaryKeyConstraint('usbid')
    )
    op.create_table('carnet_has_punto_acceso',
    sa.Column('carnet_usbid', sa.String(length=10), nullable=False),
    sa.Column('punto_acceso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carnet_usbid'], ['carnet.usbid'], ),
    sa.ForeignKeyConstraint(['punto_acceso_id'], ['punto_acceso.id'], ),
    sa.PrimaryKeyConstraint('carnet_usbid', 'punto_acceso_id')
    )
    op.create_table('cuenta_saldo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saldo_actual', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('carnet_usbid', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['carnet_usbid'], ['carnet.usbid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carnet_usbid')
    )
    op.create_table('persona',
    sa.Column('cedula', sa.String(length=15), nullable=False),
    sa.Column('carnet_usbid', sa.String(length=45), nullable=True),
    sa.Column('nacionalidad_id', sa.Integer(), nullable=True),
    sa.Column('nombres', sa.String(length=60), nullable=False),
    sa.Column('apellidos', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('direccion', sa.String(length=150), nullable=True),
    sa.Column('sexo', sa.Enum('M', 'F', name='sexoenum'), nullable=False),
    sa.Column('telefono_1', sa.String(length=20), nullable=True),
    sa.Column('telefono_2', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('discapacidad', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['carnet_usbid'], ['carnet.usbid'], ),
    sa.ForeignKeyConstraint(['nacionalidad_id'], ['nacionalidad.id'], ),
    sa.PrimaryKeyConstraint('cedula'),
    sa.UniqueConstraint('email')
    )
    op.create_table('foto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_cedula', sa.String(length=15), nullable=False),
    sa.Column('foto_path', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['persona_cedula'], ['persona.cedula'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona_tiene_afiliacion',
    sa.Column('persona_cedula', sa.String(length=30), nullable=False),
    sa.Column('afiliacion_id', sa.Integer(), nullable=False),
    sa.Column('status_persona_id', sa.Integer(), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=False),
    sa.Column('observaciones_desincorporacion', sa.String(length=300), nullable=True),
    sa.Column('fecha_desincorporacion', sa.Date(), nullable=True),
    sa.Column('fecha_incorporacion', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['afiliacion_id'], ['afiliacion.id'], ),
    sa.ForeignKeyConstraint(['persona_cedula'], ['persona.cedula'], ),
    sa.ForeignKeyConstraint(['sede_id'], ['sede.id'], ),
    sa.ForeignKeyConstraint(['status_persona_id'], ['status_persona_afiliacion.id'], ),
    sa.PrimaryKeyConstraint('persona_cedula', 'afiliacion_id')
    )
    op.create_table('vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_cedula', sa.String(length=15), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('tipo_vehiculo', sa.Enum('Automovil', 'Motocicleta', 'Autobus', 'Van', 'Bicicleta', name='tipovehiculoenum'), nullable=True),
    sa.Column('marca', sa.String(length=45), nullable=False),
    sa.Column('modelo', sa.String(length=45), nullable=False),
    sa.Column('color', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['persona_cedula'], ['persona.cedula'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('estudiante_info',
    sa.Column('persona_tiene_afiliacion_persona_cedula', sa.String(length=30), nullable=False),
    sa.Column('persona_tiene_afiliacion_afiliacion_id', sa.Integer(), nullable=False),
    sa.Column('es_deportista', sa.Boolean(), nullable=True),
    sa.Column('autorizado_desayuno', sa.Boolean(), nullable=True),
    sa.Column('autorizado_almuerzo', sa.Boolean(), nullable=True),
    sa.Column('autorizado_cena', sa.Boolean(), nullable=True),
    sa.Column('tad', sa.String(length=45), nullable=True),
    sa.Column('trd', sa.String(length=45), nullable=True),
    sa.Column('taa', sa.String(length=45), nullable=True),
    sa.Column('tra', sa.String(length=45), nullable=True),
    sa.Column('tac', sa.String(length=45), nullable=True),
    sa.Column('trc', sa.String(length=45), nullable=True),
    sa.Column('carrera_codigo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carrera_codigo'], ['carrera.codigo'], ),
    sa.ForeignKeyConstraint(['persona_tiene_afiliacion_persona_cedula', 'persona_tiene_afiliacion_afiliacion_id'], ['persona_tiene_afiliacion.persona_cedula', 'persona_tiene_afiliacion.afiliacion_id'], ),
    sa.PrimaryKeyConstraint('persona_tiene_afiliacion_persona_cedula', 'persona_tiene_afiliacion_afiliacion_id')
    )
    op.create_table('trabajador_info',
    sa.Column('persona_tiene_afiliacion_persona_cedula', sa.String(length=30), nullable=False),
    sa.Column('persona_tiene_afiliacion_afiliacion_id', sa.Integer(), nullable=False),
    sa.Column('codtpe', sa.Integer(), nullable=False),
    sa.Column('sueldo', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('bono', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('tad', sa.String(length=45), nullable=True),
    sa.Column('trd', sa.String(length=45), nullable=True),
    sa.Column('taa', sa.String(length=45), nullable=True),
    sa.Column('tra', sa.String(length=45), nullable=True),
    sa.Column('tac', sa.String(length=45), nullable=True),
    sa.Column('trc', sa.String(length=45), nullable=True),
    sa.Column('autorizado_desayuno', sa.Boolean(), nullable=True),
    sa.Column('autorizado_almuerzo', sa.Boolean(), nullable=True),
    sa.Column('autorizado_cena', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['persona_tiene_afiliacion_persona_cedula', 'persona_tiene_afiliacion_afiliacion_id'], ['persona_tiene_afiliacion.persona_cedula', 'persona_tiene_afiliacion.afiliacion_id'], ),
    sa.PrimaryKeyConstraint('persona_tiene_afiliacion_persona_cedula', 'persona_tiene_afiliacion_afiliacion_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trabajador_info')
    op.drop_table('estudiante_info')
    op.drop_table('vehiculo')
    op.drop_table('persona_tiene_afiliacion')
    op.drop_table('foto')
    op.drop_table('persona')
    op.drop_table('cuenta_saldo')
    op.drop_table('carnet_has_punto_acceso')
    op.drop_table('usuario')
    op.drop_table('rol_has_permisos')
    op.drop_table('carnet')
    op.drop_table('acceso')
    op.drop_table('status_persona_afiliacion')
    op.drop_table('status_carnet')
    op.drop_table('sede')
    op.drop_table('rol')
    op.drop_table('punto_acceso')
    op.drop_table('permisos')
    op.drop_table('nacionalidad')
    op.drop_table('departamento')
    op.drop_table('carrera')
    op.drop_table('afiliacion')
    # ### end Alembic commands ###
